spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn

management:
  endpoint:
    health:
      show-details: never
