CREATE TABLE IF NOT EXISTS processos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_processo VARCHAR(20) NOT NULL,
    comarca VARCHAR(255),
    vara VARCHAR(255),
    tribunal VARCHAR(255),
    grau VARCHAR(255),
    orgao_julgador VARCHAR(255),
    classe VARCHAR(255),
    sistema VARCHAR(255),
    formato VARCHAR(255),
    data_ajuizamento VARCHAR(255),
    ultima_atualizacao VARCHAR(255),
    CONSTRAINT uk_processo_numero UNIQUE (numero_processo)
);

CREATE TABLE IF NOT EXISTS imoveis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(255),
    endereco VARCHAR(1000),
    numero VARCHAR(255),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    cep VARCHAR(255),
    valor_avaliacao NUMERIC(15, 2),
    processo_id BIGINT NOT NULL,
    CONSTRAINT fk_imovel_processo
        FOREIGN KEY (processo_id) REFERENCES processos (id)
);

CREATE TABLE IF NOT EXISTS leiloes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abertura1_praca TIMESTAMP,
    fechamento1_praca TIMESTAMP,
    lance_inicial1_praca NUMERIC(15, 2),
    abertura2_praca TIMESTAMP,
    fechamento2_praca TIMESTAMP,
    lance_inicial2_praca NUMERIC(15, 2),
    percentual_desconto_fonte INTEGER,
    lance_minimo NUMERIC(15, 2),
    incremento NUMERIC(15, 2),
    comissao_percentual NUMERIC(5, 2),
    status_leilao VARCHAR(255),
    resultado_leilao VARCHAR(255),
    imovel_id BIGINT NOT NULL,
    CONSTRAINT fk_leilao_imovel
        FOREIGN KEY (imovel_id) REFERENCES imoveis (id)
);

CREATE TABLE IF NOT EXISTS fontes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(255) NOT NULL,
    origem_nome VARCHAR(255) NOT NULL,
    url_origem VARCHAR(2000),
    data_captura TIMESTAMP NOT NULL,
    leilao_id BIGINT,
    processo_id BIGINT,
    CONSTRAINT uk_fonte_url UNIQUE (url_origem),
    CONSTRAINT fk_fonte_leilao
        FOREIGN KEY (leilao_id) REFERENCES leiloes (id),
    CONSTRAINT fk_fonte_processo
        FOREIGN KEY (processo_id) REFERENCES processos (id)
);

CREATE TABLE IF NOT EXISTS acompanhamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imovel_id BIGINT NOT NULL,
    status_pipeline VARCHAR(255) NOT NULL,
    data_identificacao TIMESTAMP NOT NULL,
    ultima_verificacao TIMESTAMP NOT NULL,
    observacao VARCHAR(2000),
    ativo BOOLEAN NOT NULL,
    CONSTRAINT uk_acompanhamento_imovel UNIQUE (imovel_id),
    CONSTRAINT fk_acompanhamento_imovel
        FOREIGN KEY (imovel_id) REFERENCES imoveis (id)
);

CREATE TABLE IF NOT EXISTS historicos_acompanhamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acompanhamento_id BIGINT NOT NULL,
    data_evento TIMESTAMP NOT NULL,
    status_pipeline VARCHAR(255) NOT NULL,
    status_leilao VARCHAR(255),
    resultado_leilao VARCHAR(255),
    origem VARCHAR(255) NOT NULL,
    descricao VARCHAR(2000),
    CONSTRAINT fk_historico_acompanhamento
        FOREIGN KEY (acompanhamento_id) REFERENCES acompanhamentos (id)
);

CREATE TABLE IF NOT EXISTS execucoes_descoberta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fonte VARCHAR(120) NOT NULL,
    inicio TIMESTAMP NOT NULL,
    termino TIMESTAMP,
    duracao_ms BIGINT,
    origem VARCHAR(30) NOT NULL,
    status VARCHAR(40) NOT NULL,
    total_encontrado INTEGER NOT NULL,
    total_elegivel INTEGER NOT NULL,
    total_importado INTEGER NOT NULL,
    total_duplicado INTEGER NOT NULL,
    total_descartado INTEGER NOT NULL,
    total_falha INTEGER NOT NULL,
    erro_resumo VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS resultados_lote_descoberta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execucao_id BIGINT NOT NULL,
    titulo VARCHAR(500),
    cidade VARCHAR(120),
    url_original VARCHAR(2000),
    url_normalizada VARCHAR(2000),
    numero_processo VARCHAR(30),
    decisao VARCHAR(20) NOT NULL,
    motivo VARCHAR(1000) NOT NULL,
    imovel_id BIGINT,
    CONSTRAINT fk_resultado_execucao
        FOREIGN KEY (execucao_id) REFERENCES execucoes_descoberta (id),
    CONSTRAINT fk_resultado_imovel
        FOREIGN KEY (imovel_id) REFERENCES imoveis (id)
);

CREATE INDEX IF NOT EXISTS idx_imovel_processo
    ON imoveis (processo_id);
CREATE INDEX IF NOT EXISTS idx_leilao_imovel
    ON leiloes (imovel_id);
CREATE INDEX IF NOT EXISTS idx_fonte_leilao
    ON fontes (leilao_id);
CREATE INDEX IF NOT EXISTS idx_historico_acompanhamento_data
    ON historicos_acompanhamento (acompanhamento_id, data_evento DESC);
CREATE INDEX IF NOT EXISTS idx_execucao_inicio
    ON execucoes_descoberta (inicio DESC);
CREATE INDEX IF NOT EXISTS idx_resultado_execucao
    ON resultados_lote_descoberta (execucao_id, id);
